### ISSUE TITLE
Original PNG resolution is modified

### ISSUE THREAD

**Issue by gradha** [pornel/pngquant#123]
On a macbook pro retina PNG screen captures have 144 dpi, but after running pngquant on them the dpi are reduced to 72, which makes the images look twice as big. Attaching a window capture and its modification.
![modified](https://cloud.githubusercontent.com/assets/101927/4483560/77a8ea72-49b2-11e4-824c-38e02f185bb1.png)
![original](https://cloud.githubusercontent.com/assets/101927/4483561/7838c6d8-49b2-11e4-92e5-7c244cb6fa47.png)
File generated with 2.3.0.

**Comment by designorant** [comment]
The way OSX handles this does make one weep indeed but the issue is partially about pngquant changing 144 to 72 dpi. Surely this is a bug?

**Comment by pornel** [comment]
As far as I'm aware `pngquant` correctly preserves the standard DPI information embedded in PNG files when it's using libpng 1.5+.

However, OS X does not support DPI metadata in PNG. It doesn't write it. It doesn't read it.

Instead, OS X only uses its own *undocumented* non-standard hidden HFS-only metadata that gets lost when a file is copied or replaced by a program that isn't Apple's ([see my previous comment](https://github.com/pornel/pngquant/issues/123#issuecomment-58973503)).

I really don't want to add special support for OS X's hidden "this is a screenshot" flag, because it's a such a stupid and fragile hack.

**Comment by designorant** [comment]
> As far as I'm aware pngquant correctly preserves the standard DPI information embedded in PNG files when it's using libpng 1.5+.

Please excuse my ignorance here but is DPI information different to DPI metadata or the 'numbers' you mentioned earlier? Am I wrong to think that DPI information/metadata/numbers is one thing, and the xattr is another? The former seems constant and PNG-specific, the latter is OS X specific and helps to present the PNG more 'natively'. Reading your comments I find the line between supporting and ignoring DPI a bit blurry too.

> I'm testing on OSX Yosemite and quick look and Preview ignore DPI metadata (they will show you the numbers, but displayed size is wrong unless xattrs are copied)

This is exactly the reason why I suspect that pngquant has a bug. The numbers are right so why does pngquant change them?

> However, OS X does not support DPI metadata in PNG. It doesn't write it. It doesn't read it.
> Instead, OS X only uses its own undocumented non-standard hidden HFS-only metadata that gets lost when a file is copied or replaced by a program that isn't Apple's (see my previous comment).

Again, I understand what OS X does there visual-wise (I followed your quick test prior to my original question). What I cannot understand is why would the 144 dpi be changed to 72 dpi by pngquant?

Please consider the following:
- Visual side aside, I open both `NiceHighResScreenShot.png` and `Copy.png` in Preview. Inspector shows 144 dpi.
- I open both files in Adobe Photoshop CC (2014.2.2) and Photoshop says they are both 144 dpi. When I save both (unless with 'Save for Web' mode) they are kept with 144 dpi.
- When I run both through pngquant (2.3.1) they are saved as 72 dpi ones.

While this little detail does not do anything visual-wise at this point, it may be important for when software gets smarter in the high res future to come.

**Comment by pornel** [comment]
By PNG DPI metadata I mean `pHYs` chunk in the PNG file. Yes, it's different from OS X's extended attribute `com.apple.metadata:kMDItemIsScreenCapture` that is added to screenshots on HFS disks.

>  The numbers are right so why does pngquant change them?

You see different DPI, but it's not because pngquant changed it, but because OS X does its own magical thing that works only on specially blessed individual instances of files on HFS disks.

It's a similar problem to files losing their magic behaviors in Mac OS classic due to resource forks.

Even creation of perfect byte-by-byte copy of the file's contents will appear to change DPI of the file — a perfect copy of that file! Changed!

Please try to understand exactly what happens here:

```sh
cat NiceHighResScreenShot.png > Copy.png
shasum NiceHighResScreenShot.png Copy.png
```

It will take `NiceHighResScreenShot.png` and create a perfect copy, byte by byte. You'll get two files that are identical.

You can verify this with shasum:

> 448ec5b77971cea91b720c2d132b4e67f5622cd6 NiceHighResScreenShot.png
> 448ec5b77971cea91b720c2d132b4e67f5622cd6 Copy.png

Which is a strong guarantee that the files are absolutely identical.

And yet, Quicklook and Preview will display them at a different size! So even though the file has not changed, the DPI has changed!? Yes, that's how OS X does it!

**Comment by designorant** [comment]
Third time's a charm, they say but maybe I did not make myself clear enough:

**My comments are *not* about OS X**. They are *not* about how PNGs look / get rendered. They are about **pngquant** itself.

I have got a PNG file saved with 144 DPI. It is *not* a screenshot made on Retina OS X. It is a random picture of a [random cat](http://random.cat/) that I downloaded, converted into PNG and changed the DPI value in Photoshop. I do not expect the image to be shown relative to my system's resolution. I am used to a fact that almost everything is rendered at 72dpi anyway. The topic of the actual DPI and screens is a separate, somewhat convoluted story.

Now, when I take that image and put it through pngquant, it changes its 144 DPI to 72 DPI.

**Comment by pornel** [comment]
Right, so for a random cat and systems that respect PNG's pHYs chunk you need pngquant that uses libpng 1.5 or higher, and it'll work:

Take a [random cat with DPI 144 via pHYs chunk](https://cloud.githubusercontent.com/assets/72159/6384313/c6fede24-bd52-11e4-83ce-21d90c78826c.png)

Non-OS X, non-Debian version of pngquant:

> ./pngquant
pngquant, 2.3.4 (September 2014), by Greg Roelofs, Kornel Lesinski.
   Compiled with SSE instructions.
   Using libpng 1.6.12.

```sh
$ ./pngquant /tmp/cat.png
```

and you get [cat-fs8.png](https://cloud.githubusercontent.com/assets/72159/6384323/e62673e8-bd52-11e4-8acb-a034f0c5f189.png) that has the right chunk preserved:


![screen shot 2015-02-26 at 01 02 25](https://cloud.githubusercontent.com/assets/72159/6384336/25a1f560-bd53-11e4-813a-e5efdfb63dff.png)

**Comment by designorant** [comment]
Very interesting! Thanks!

**Comment by songgeb** [comment]
cat NiceHighResScreenShot.png > Copy.png

Now (mac os 10.13.2) the Copy.png's dpi is equal to NiceHighResScreenShot, but dpi after pngquant compression is still changed.

Is is a bug?

**Comment by songgeb** [comment]
`cat NiceHighResScreenShot.png > Copy.png`

Now(mac os 10.13.2) the dpi of Copy.png is not be changed. But dpi of image through pngquant is still be changed.

It is so sad....

**Comment by ypresto** [comment]
Still `xattr -c NiceHighResScreenShot.png` changes DPI of image rendered in quick look.
But resolution metadata is still kept  of same 144x144dpi (ImageMagick's `identify -verbose`) after removing xattr.

----

> But dpi of image through pngquant is still be changed.

At least my macOS environment, metadata is changed but actual DPI is kept.

Original:

```
Image:
  Filename: ScreenShotOnMac.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 1898x922+0+0
  Resolution: 144x144
  Print size: 13.1806x6.40278
  Units: PixelsPerInch
  Colorspace: sRGB
```

pngquant-ed:

```
Image:
  Filename: ScreenShotOnMac-fs8.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: PseudoClass
  Geometry: 1898x922+0+0
  Resolution: 56.69x56.69
  Print size: 33.4803x16.2639
  Units: PixelsPerCentimeter
  Colorspace: sRGB
```

As 1inch is 2.54cm, 56.69 pixel per centimeter is 144dpi.
