### ISSUE TITLE
Visual Studio project file

### ISSUE THREAD

**Issue by pornel** [pornel/pngquant#151]
Could somebody contribute a VS project file that builds (and links with libpng) libimagequant and pngquant?

I presume it'd be for VS 2013 Community Edition, unless there's a newer free one.

BTW: there's a [msvc](https://github.com/pornel/pngquant/tree/msvc) branch that should make that less painful.

**Comment by ignisf** [comment]
Can't cmake generate a VS project?

**Comment by VeryVery** [comment]
I wish someone contribute a vs2015 project.

**Comment by jibsen** [comment]
I believe there are two issues with adding a VS project:

  - You need the dependencies (libpng, zlib, and optionally lcms2), which do not come with Windows. There are various package managers that aim to fix this at some point (nuget, build2, vcpkg), but it's not really easy since you need the libraries linked to the same MSVC runtime as the application.
  - A minor issue; pngquant uses getopt which MSVC does not provide

**Comment by pornel** [comment]
Yeah. I've tried nuget's libpng a while ago, and it installed headers correctly, but not libraries (or at least I could not figure out how to link with them).

**Comment by pornel** [comment]
Obsoleted by Rust #166
