### ISSUE TITLE
Intermittent exit code 25

### ISSUE THREAD

**Issue by brianlukoff** [pornel/pngquant#175]
I'm seeing pngquant crash about 5-10% of the time when presented with a large image; reporting an exit code of 25, which I believe is a libpng error. The strange thing is that retrying pngquant with the very same image will often then succeed!

**Comment by pornel** [comment]
Are you using libpng 1.6+?

Do you get any information in stderr?

How large are the images? Are you running multiple processes in parallel?

**Comment by brianlukoff** [comment]
Thanks -- I was running libpng 1.2 (what was in the Ubuntu package manager) but just rebuilt pngquant using the latest 1.6 and so far so good. Will reopen this issue if I see the problem again!

**Comment by caub** [comment]
I had this error too, running several processes in parallel and using pngquant for single images, I solved it by processing all images with `*.png --ext .png --force`

ps: pornel, I haven't advanced with emscripten, but I'll try to do it as soon as possible, on Linux rather (because minGW sucks a bit)

**Comment by pornel** [comment]
OK, if you're seeing it intermittently when processing lots of files you may simply be running out of memory to decompress so many images at the same time.

pngquant compiled with openmp will nicely run multiple files in parallel.
