### ISSUE TITLE
pngquant doesnt work on some image, image degradation MSE=67.735 (Q=4) exceeded limit of 8.804 (72)

### ISSUE THREAD

**Issue by ntus1017** [pornel/pngquant#176]
This is sample image

![1](https://cloud.githubusercontent.com/assets/2043883/10512566/8c5df622-736b-11e5-894a-efa874cd601a.png)

output:
read 214KB file
  made histogram...68875 colors found
  selecting colors...3%
  selecting colors...6%
  selecting colors...8%
  selecting colors...11%
  selecting colors...27%
  selecting colors...43%
  selecting colors...58%
  selecting colors...74%
  selecting colors...90%
  selecting colors...100%
  moving colormap towards local minimum
  image degradation MSE=68.444 (Q=4) exceeded limit of 8.804 (72)
Skipped 1 file out of a total of 1 file.

**Comment by petrdiblik** [comment]
This is normal.
pngquant was called with min quality 72. But with 256 colors the resulting quality is just 5 and therefore the required minimum is not met.

**Comment by petrdiblik** [comment]
Or did you mean you expected a higher quality output (nominal and/or visual)? Please clarify.

**Comment by ntus1017** [comment]
I think the problem solved with lower quality parameter. My bad. Thank you for supporting.

**Comment by shalmuyakubov** [comment]
@petrdiblik , I have the same problem, PNGQuant wants to save with Q=24, but I set up min=30. 
Ok, I set the min=24 and get the result. The size is too small and the quality is too low! So why can't I force it to save a bigger file, but with higher quality? Something doesn't match up here. What limits you from making it better quality? The image obviously can be better, because now the result is so low.

**Comment by kornelski** [comment]
> So why can't I force it to save a bigger file, but with higher quality?

pngquant is limited by what the PNG format can do. PNG supports 8 and 24/32-bit color modes, and the file size is roughly proportional to number of bits per pixel.

If the image doesn't "fit" in 8-bit mode (which has a hard limit of 256 colors) the next available mode is 24-bit. So just going from 256 colors to 257 colors is close to increasing file size 3 times! At that point the trade-off between file size and quality becomes rather bad, and pngquant's core algorithm doesn't make much sense for the 24-bit mode anyway, so pngquant gives up instead of forcing square peg into a round hole.

I've written another tool that tries to make 24/32-bit PNG more compressible:

https://github.com/kornelski/mediancut-posterizer

**Comment by shalmuyakubov** [comment]
Thanks for such a clear explanation! I'll definitely try your tool.
