### ISSUE TITLE
Dull colors in pngquant output

### ISSUE THREAD

**Issue by W1zzardTPU** [pornel/pngquant#178]
It looks like there is some kind of issue with pngquant color-profiles.

    pngquant, 2.5.2 (October 2015), by Greg Roelofs, Kornel Lesinski.
    Color profiles are supported via Little CMS. Using libpng 1.6.18.

Original Image (from the official website):
![ducati_side_shadow](https://cloud.githubusercontent.com/assets/15492674/10863366/5c3b593c-7fcb-11e5-9963-9aae3d97e515.png)

  ./pngquant -fv ducati_side_shadow.png

    ducati_side_shadow.png:
      read 74KB file
      made histogram...15547 colors found
      selecting colors...4%
      selecting colors...7%
      selecting colors...28%
      selecting colors...49%
      selecting colors...52%
      selecting colors...73%
      selecting colors...94%
      selecting colors...100%
      moving colormap towards local minimum
      eliminated opaque tRNS-chunk entries...115 entries transparent
      mapped image to new colors...MSE=7.453 (Q=75)
      writing 256-color image as ducati_side_shadow-fs8.png
    No errors detected while quantizing 1 image.

Result (21.8 KB) - colors are lacking fidelity (Firefox Windows), or are too bright (Firefox OSX)
![ducati_side_shadow-fs8](https://cloud.githubusercontent.com/assets/15492674/10863368/739b0028-7fcb-11e5-81c7-e0add272a4ae.png)

Now if I do:
convert -verbose -strip ducati_side_shadow-fs8.png ducati_side_shadow2.png

    ducati_side_shadow-fs8.png PNG 288x163 288x163+0+0 8-bit DirectClass 22.4KB 0.040u 0:00.000
    ducati_side_shadow-fs8.png=>ducati_side_shadow2.png PNG 288x163 288x163+0+0 8-bit PseudoClass 256c 0.020u 0:00.030

The output is correct again on both browsers (21.8 KB):
![ducati_side_shadow2](https://cloud.githubusercontent.com/assets/15492674/10863371/c1efe3a6-7fcb-11e5-8f34-67b1b1aa0042.png)

Any ideas what's happening here?

**Comment by pornel** [comment]
Files generated by pngquant have sRGB chunk (because that's the colorspace that pngquant assumes and optimizes for).

Browsers that display it with "dull" colors probably support color profiles correctly, and other browsers display it using your monitor's color profile, and your monitor isn't calibrated for sRGB.

The images on the website have been optimized with ImageOptim, which strips all metadata including the sRGB chunk.

**Comment by W1zzardTPU** [comment]
So the correct workflow is to use pngquant and after that use some software that strips all the metadata ?

Is there any scenario in which pngquant's included metadata can be useful? If no, why even bother writing metadata? I'd expect a lot of users expect pngquant to do the right thing(tm) when at the end of the workflow

**Comment by pornel** [comment]
I'm afraid there's no one true good workflow:

- Lots of tools ignore color profiles, work in unlabelled "RGB" without gamma awareness, and end up displaying graphics in monitor's native profile, regardless of what it is. This is technically quite incorrect:
  * dark shades will be completely black for some users, and very visible posterized gray for others, and there's nothing you can do about it
  * on high gamut monitors colors will be oversaturated, sometimes so much that everything looks like drawn using fluorescent markers. Some users actually like that and Sony even sells phones where this bug is a feature :)

- The correct behavior is to read color profiles and embed color profiles. 

Pngquant is trying to balance correctness and compatibility. Pngquant supports that where possible. However, support for color profiles everywhere is generally weak, so pngquant converts images to sRGB profile, which is the most common one. The effect is that the image looks the same in all color-profile-supporting software, and in color-ignorant software on sRGB monitors.

**Comment by W1zzardTPU** [comment]
The motorcycle original image in first post is sRGB, shouldn't the colors stay unchanged in that case?

**Comment by pornel** [comment]
No, the source image was unlabelled, so its profile would be whatever any software decides (some decide sRGB, some decide monitor's native profile).

**Comment by W1zzardTPU** [comment]
```[root@3ccee13c096b /]# identify -verbose Ducati_side_shadow.png
Image: Ducati_side_shadow.png
  Format: PNG (Portable Network Graphics)
  Class: DirectClass
  Geometry: 288x163+0+0
  Resolution: 72x72
  Print size: 4x2.26389
  Units: Undefined
  Type: TrueColorAlpha
  Endianess: Undefined
  Colorspace: sRGB
``` 

So I guess this is a case of ImageMagick not finding a color space and just assuming sRGB ?

**Comment by pornel** [comment]
Are we talking about the same image? I've inspected https://cloud.githubusercontent.com/assets/15492674/10863366/5c3b593c-7fcb-11e5-9963-9aae3d97e515.png and it didn't have any color-related chunks.

**Comment by pornel** [comment]
but yes, ImageMagick shows sRGB anyway, so it's assuming lack of color profile information means sRGB.

**Comment by pornel** [comment]
In 2.6 I've tweaked handling of unlabelled colors. Now images that had no color profile information at all won't get sRGB chunk written, which should keep colors consistent.
