### ISSUE TITLE
Already premultiplied alpha

### ISSUE THREAD

**Issue by damucz** [pornel/pngquant#184]
Hi.

Is there an option to pass the images with already premultiplied alpha into the pngquant?
Passing such images currently break alpha channel.

I'm not sure why. I found the gamma correction premultiply the alpha again, which could be the issue. I have looked at the sources trying to disable this, but didn't find other way than remove lines from to_f and to_rgb, because they are used heavily over the code.

If the gamma is really the issue, I would welcome a command line parameter to tell pngquant the alpha is already premultiplied.

Thank you.
Dan

**Comment by pornel** [comment]
There is no such option. pngquant supports PNG only, and PNG does not support premultiplied alpha.

I could add a new input format to libimagequant, but I'd rather not create a new PNG-command-line-switch hybrid format.

**Comment by damucz** [comment]
Understood. I'm probably going to do a custom modification just for our purposes/toolchain. Thanks for the great tool.

**Comment by eodabash** [comment]
I realize this is a long since closed issue 😁 but out of curiosity did you ever complete this modification @damucz? I browsed through your fork a bit but didn't see anything obvious.

We're running into the exact same issue I think, with premultiplied input images having something changed in their alpha channel which makes them no longer render correctly in our game engine. Interestingly in pngquant 2.0.0 there is no such problem, but only after updating to a more recent build did this start happening.
