### ISSUE TITLE
Request: separate CLI from pngquant functionality?

### ISSUE THREAD

**Issue by abelnation** [pornel/pngquant#187]
It would be awesome to be able to execute the same functionality that the pngquant cli program executes, but directly from c/c++ code without starting a separate process.  It would enable writing direct native wrappers for pngquant in other languages (e.g. python, node.js)

**Comment by pornel** [comment]
Please see libimagequant: https://pngquant.org/lib/

**Comment by abelnation** [comment]
But doesn't the pngquant cli program do much more than libimagequant?  e.g. rwpng.h/c has quite a bit going on inside that could be contained in a lib?  Perhaps I'm misunderstanding how the components work together...

**Comment by pornel** [comment]
All the optimisation secret sauce is in the library. pngquant executable is an interface for it that adds loading and saving of images. 

rwpng has a bit of logic to load PNG properly with color profiles on any platform, but OTOH its equivalent for OS X is only a [few lines of code](https://github.com/pornel/pngquant/blob/master/rwpng_cocoa.m).

I'm assuming that if you have an existing C/C++ program for image manipulation, you already have some sort of image I/O implemented, and a C program operates on in-memory bitmaps, rather than file paths.

**Comment by quiret** [comment]
libimagequant is a really powerful. I use it for general color palette generation and remapping independent from pngquant. Totally recommend you to write your own CLI or something, because the API is straight-forward!

**Comment by pornel** [comment]
So I think libimagequant is providing the functionality. There is some useful code in rwpng, but it's "just" proper reading of PNG files, not quantization. And rwpng is reusable in other projects, e.g. I use it in dssim.
