### ISSUE TITLE
content instead of path

### ISSUE THREAD

**Issue by Khav21** [pornel/pngquant#203]
Pngquant has the following example for php

   ` $compressed_png_content = shell_exec("pngquant --quality=$min_quality-$max_quality - < ".escapeshellarg(    $path_to_png_file));`

I want to replace $path_of_file with the actual content.

This will avoid wasting I/O when converting a file from one format to png and then optimize it

What will be the new shell_exec() command in that situation

**Comment by pornel** [comment]
I didn't suggest that, because it's very cumbersome in PHP. You will have to [use proc_open and pipes](http://php.net/manual/en/function.proc-open.php).

On most servers it won't save you more than 1% of processing time, because cached I/O is quite fast compared to amount of computation needed for compression.

**Comment by Khav21** [comment]
Thanks for the fast response 

It would be nice if you could add an option for content directly as well in future

Consider the following scenario
 
POST(RAM) -->Convert to PNG (RAM) -->Store on disk --> Pngquant -->Store on disk

If i could make pngquant accept content from RAM , I would store to disk only once.

POST(RAM) -->Convert to PNG (RAM) --> Pngquant(RAM) -->Store on disk

Kind Regards

**Comment by pornel** [comment]
On modern systems it's very likely that it won't make any difference at all, and the data would be in RAM at all times, even when you create a temporary file.

That's because many Linuxes use `tmpfs`, which stores files in RAM rather than a disk. Even on real disk-backed folders the file may be written to RAM cache first and not flushed to disk if you delete it soon afterwards (without something calling `fsync` in between).
