### ISSUE TITLE
Linux sover

### ISSUE THREAD

**Issue by pornel** [pornel/pngquant#227]
In 2.8.0 I've added new functions. All old ones are still available. Should this affect dynamic library's SO version?

**Comment by pornel** [comment]
@sergiomb2?

**Comment by sergiomb2** [comment]
I tested 2.8.1 and compiles fine , now I have to download 2 files : 
https://github.com/pornel/pngquant/archive/2.8.1.tar.gz
https://github.com/ImageOptim/libimagequant/archive/2.8.1.tar.gz

https://pkgs.fedoraproject.org/cgit/rpms/pngquant.git/commit/?id=fcfce9d374d48338d9fbbc22389934894ad8c6fd

**Comment by pornel** [comment]
Thanks Sérgio. Download of 2 archives is OK. I'll need to remember to tag both.

What about the build of shared library? Is it OK to keep it as `libimagequant.so.0`? I don't know what are the rules of SO versioning. Does addition of new functions require changing it to `libimagequant.so.1` or such?

**Comment by Hello71** [comment]
soname change is required iff ABI for old programs changes. it is intended to address the issue of "install old library, compile program, upgrade library (new function takes float instead of int), program silently breaks". if you do "install new library, compile program (using new functions), downgrade library (removing new functions)", then the program will say "undefined symbol", no soname required. similar behavior occurs, of course, with "install old library, compile program using new functions", then it fails at compile time, no soname required.

**Comment by pornel** [comment]
Thank you.
