### ISSUE TITLE
pngquant v2.10.0 windows not compatible with  the version of Windows you're running

### ISSUE THREAD

**Issue by phonphen** [pornel/pngquant#253]
i have downloaded pngquant v2.10.0 from https://pngquant.org/pngquant-windows.zip
but is not compatible with my windows version

my os: windows 7 x86sp1

![img45536 1](https://user-images.githubusercontent.com/25279951/27791237-48a1392a-601e-11e7-8aa8-9d13ed4571f0.png)

**Comment by pornel** [comment]
This is because you have an old, less secure version of Windows. 

If your computer less than 11 years old it should be running 64-bit OS instead: https://www.backblaze.com/blog/64-bit-os-vs-32-bit-os/

**Comment by phonphen** [comment]
that mean pngquant 2,10 only for windows x64 ?
not like previous version 2.81 that can run in windows x86

**Comment by pflacson** [comment]
I've the same thing on my computer (so I can't use it), and this on my laptop (Windows 7 Home Edition 64 bits)!!!
![sans titre](https://user-images.githubusercontent.com/23261992/27800948-33007120-600b-11e7-9241-9e951315a6c6.jpg)
I had to download this : https://www.microsoft.com/en-US/download/details.aspx?id=40784

**Comment by pornel** [comment]
I've removed use of the DLL. Please download again and see if it works.

I'm also worried that Windows SmartScreen may be preventing pngquant from writing files. If files don't appear and it quits with "can't write file.png.tmp", then it's probably Windows blocking it. I'm not sure what to do about that :(

**Comment by pflacson** [comment]
Yes it's working, thank you!! but it's less simple to use pngquant now than before (I have your precedent 2.8.1 too). I've a error when I prompt "pngquant *.png"...can't find files.... and I have performance problem too with big pics but maybe it's wanted for pngquant 2.10 because sometimes it compress more?? in complement can you add the folder support ?? thank you!!

**Comment by pornel** [comment]
Please open new issues for performance problems and problems with opening files.

**Comment by pflacson** [comment]
Hello pornel !
Can you provide Pngquant 2.10.1 32 bits for Windows ?

**Comment by pornel** [comment]
Sorry, I won't.

Given that the last 32-bit Intel CPU was produced almost 10 years ago, and the last good one is 15 years old, it's really time to stop using 32-bit software.

**Comment by pflacson** [comment]
Hello again,
I just wanted to do test with the new version if it's possible.... I have 2.8.3 32bits and it's more easy to use for my scripts (pngquant *.png don't find any files on last version).. Also it's possible 32 bits with big image done the job quicker than 64 bits ?? (my system has 64 bits)... or it's because you change the compression level ?
Thank you !

**Comment by Furniel** [comment]
@pflacson 
Here is 2.10.2 32bit windows version of pngquant(compiled with mingw, uses libpng 1.6.34, zlib 1.2.11 and Little CMS):
[pngquant_x86.zip](https://github.com/pornel/pngquant/files/1358922/pngquant_x86.zip)

**Comment by pornel** [comment]
@Furniel  Thanks for the build!

@pflacson No, 32-bit executables are generally slower on x86. I don't know about Windows, but on most other OS-es they also harm performance of the entire system, because all system libraries need to be duplicated or emulated for the legacy executables.

**Comment by pflacson** [comment]
Thank you very much Furniel !!
Pornel, I don't understand why then this compilation is quicker on my 64bit system ??
And pngquant *.png works with x86 ! Strange....

**Comment by pornel** [comment]
On your 32-bit system it won't, because the system pretends your CPU is old and doesn't use it's faster mode of operation.

Only if you have x86-64 CPU, and 64-bit operating system on it, and use a 64-bit executable (i.e. *everything* 64-bit, nothing 32-bit), only then it will unlock a faster mode of operation of your CPU.

**Comment by pflacson** [comment]
I've a lot of big Png32 images to convert lije this http://www.powerpointhintergrund.com/uploads/2017/05/pics-photos-teal-abstract-background-32.png

I'm working on my laptop Windows 7 Home Edition 64 bits and I've just compared :+1: 
Pngquant 64-bit https://pngquant.org/pngquant-windows.zip
Pngquant 32-bit Furniel
The CPU N3710 Intel Pentium 64-bit
So everything is 64 bits!!

Pngquant 32-bit compress the new Png quicker than the Pngquant 64-bit!! I don't understand why the 32-bit is quicker and also the 2.8.3 (32-bit) is too!! It's not a big deal but I'm curious.... I always prefer 64-bit version because it's quicker on other programs.. but not here!! The difference is just few seconds for one file.. but I've like 3000 Png like this.... also the result is not exactly the same sometimes!!
Just tell me if I do this wrong and thank you for your wonderful program!!!

**Comment by Furniel** [comment]
@pflacson 
Made own quick test(tested compression of 40mp image) of my x86 version, my x64 version and official version of pngquant:
Time of image compression:
21 sec  - original x64 binary
15 sec - my own x64 binary
20 sec - my own x86 binary

I don't know with what gcc version and optimization flags official binary was compiled, but i used gcc 7 and O3, flto and profile-guided optimization.

My x64 binary if you want make own tests:
[pngquant_x64.zip](https://github.com/pornel/pngquant/files/1366328/pngquant_x64.zip)

**Comment by pflacson** [comment]
Thank you Furniel !
I confirm it's more quicker with your binary x64 !!

**Comment by Furniel** [comment]
@phonphen 
Recompiled my binaries(enabled open mp support - missed thap pngquant supports this during first compilation. Now binaries can use all cpu cores).

Remade tests:

One image processing:
21 sec - original x64 binary
13 sec - my new x64 binary with OMP enabled
15 sec - my old x64 binary
17 sec - my new x86 binary with OMP enabled
20 sec - my old x86 binary

Batch image processing(set of 10 different images, tested on core i7 with 4 cores and 8 threads):
error   - original x64 binary can't find path and for some reason doesn`t work in batch mode
17 sec - my new x64 binary with OMP enabled
46 sec - my old x64 binary
24 sec - my new x86 binary with OMP enabled
64 sec - my old x86 binary

New binaries for tests:
[pngquant_x86_omp.zip](https://github.com/pornel/pngquant/files/1369666/pngquant_x86_omp.zip)
[pngquant_x64_omp.zip](https://github.com/pornel/pngquant/files/1369668/pngquant_x64_omp.zip)

**Comment by Divya063** [comment]
@pornel @Furniel While running the command pngquant *.png in command line I'm getting this error  error: cannot open *.png for reading
I'm using Windows 10 64 bit
