### ISSUE TITLE
Different version generate different result

### ISSUE THREAD

**Issue by littleboss** [pornel/pngquant#281]
Once I use pngquant v-2.9.1, i compress my resources for online, but after i upgrade pngquant to v2.11.4, i compress them but generate different result and the compression parameters were kept same

**Comment by pornel** [comment]
Yes, that's entirely expected. The versions have tweaks to the algorithm. They also can be compiled with or without support for color profiles, which significantly changes some images.

**Comment by littleboss** [comment]
thanks for your reply, is there any way to keep the same output for my different versions?  for example, as you said "with or without support for color profiles" ? With different output, i must update many files online. thanks

**Comment by pornel** [comment]
No, if different versions were to have identical output it would mean it's always the same code that does the same thing, and it would forbid any improvements.

So expect all versions to always generate different (generally better) outputs.

You can check whether profiles are enabled by running `pngquant -h`.

**Comment by littleboss** [comment]
thanks, i met a new issue, i use same version under different macosx version(10.12 and  10.13), the same resources produce different outputs, maybe because of different xcode version

**Comment by pornel** [comment]
Even the same source code of pngquant can produce different outputs on the same machine, depending on version of your compiler (due to ffast-math setting and use of `rand()`).

You can't rely on same output at all.

You can use visual comparison tool like DSSIM if you want to ensure output matches some expectation, but you need to accept it's almost random.
