### ISSUE TITLE
Washed out color on OS X Mavericks

### ISSUE THREAD

**Issue by felixakiragreen** [pornel/pngquant#56]
When I optimized PNGs on Mavericks it really desaturates the colors. I tested this across many different PNGs and it does it to all of them.

![screen shot 2013-10-25 at 10 36 37 pm](https://f.cloud.github.com/assets/1843672/1412732/f6dd8910-3de7-11e3-8f92-84ea4b5bd762.png)

**Comment by marcedwards** [comment]
I think there’s two issues here:

1. Incorrect displaying of PNG8 (which I've seen from many sources, not just pngquant).
2. PNGs with no ICC profile included are now considered to be sRGB by Preview, Safari (version 6 and above) and other apps.

The second issue means there will be an sRGB to the correct display profile conversion. Apple’s built-in standard profiles are typically quite close to sRGB, so the conversion is minimal, but definitely still there. At this time, Chrome displays PNGs without conversion, so that might be a better tool to use when comparing images than Preview.

**Comment by pornel** [comment]
The issue reported in this bug has been fixed on OS X 10.9.2. It was due to gamma correction being applied twice.

**Comment by marcedwards** [comment]
Ok, great to know. Thanks.
